ingress:
  hosts:
    - host: api.dev.nimbuscore.io
      paths:
        - path: /
          pathType: Prefix

config:
  logLevel: debug
  oidc:
    issuer: http://dex:5556/dex
    clientId: nimbuscore
    redirectUrl: http://localhost:5173
    externalIssuer: http://localhost:5556/dex
  rabbitmq:
    url: amqp://user:changeme@rabbitmq:5672
  ingress:
    host: nimbuscore.local

monitoring:
  serviceMonitor:
    enabled: false

api:
  replicas: 1
  autoscaling:
    enabled: false

operator:
  replicas: 1

workspaceManager:
  replicas: 1

postgresql:
  enabled: true
  auth:
    username: nimbuscore
    password: nimbuscore
    database: nimbuscore
  primary:
    persistence:
      size: 5Gi
    initdb:
      scriptsConfigMap: nimbuscore-db-init

redis:
  enabled: true
  auth:
    password: nimbuscore
  master:
    persistence:
      size: 2Gi

rabbitmq:
  enabled: false
  auth:
    username: user
    password: changeme
