ingress:
  hosts:
    - host: api.dev.nimbuscore.io
      paths:
        - path: /
          pathType: Prefix

config:
  logLevel: debug
  oidc:
    issuer: http://host.docker.internal:5556/dex
    clientId: nimbuscore
    redirectUrl: http://nimbuscore.local/auth/callback
  ingress:
    host: nimbuscore.local

monitoring:
  serviceMonitor:
    enabled: false

api:
  replicas: 1
  autoscaling:
    enabled: false

operator:
  replicas: 1

workspaceManager:
  replicas: 1

postgresql:
  enabled: true
  auth:
    username: nimbuscore
    password: nimbuscore
    database: nimbuscore
  primary:
    persistence:
      size: 5Gi

redis:
  enabled: true
  auth:
    password: nimbuscore
  master:
    persistence:
      size: 2Gi

rabbitmq:
  enabled: true
  auth:
    username: user
    password: changeme
  image:
    registry: docker.io
    repository: bitnami/rabbitmq
    tag: 4.0.5-debian-12-r7
  initContainerImage:
    registry: docker.io
    repository: bitnami/rabbitmq
    tag: 4.0.5-debian-12-r7
