FROM golang:1.26.5-alpine AS builder
WORKDIR /build

COPY apps/operator apps/operator
COPY pkg/operator pkg/operator
COPY pkg/api pkg/api

WORKDIR /build/apps/operator
RUN go mod download
RUN go build -o /bin/operator ./cmd

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=builder /bin/operator /operator
USER nonroot:nonroot
EXPOSE 8080
ENTRYPOINT ["/operator"]
