apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nimbuscore.operator.fullname" . }}
  labels: {{ include "nimbuscore.operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "nimbuscore.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: operator
  template:
    metadata:
      labels: {{ include "nimbuscore.operator.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-operator.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ include "nimbuscore.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      containers:
        - name: operator
          image: "{{ .Values.image.registry }}/nimbuscore-operator:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "nimbuscore.operator.fullname" . }}
            - secretRef:
                name: {{ include "nimbuscore.fullname" . }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources: {{ toYaml .Values.operator.resources | nindent 12 }}
