apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nimbuscore.fullname" . }}
  labels: {{ include "nimbuscore.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.secrets.jwt | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
  DATABASE_URL: {{ include "nimbuscore.db.url" . }}
  REDIS_URL: {{ include "nimbuscore.redis.url" . }}
  RABBITMQ_URL: {{ include "nimbuscore.rmq.url" . }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.awsAccessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.awsSecretAccessKey | quote }}
  RESTIC_PASSWORD: {{ .Values.secrets.resticPassword | quote }}
