apiVersion: v1
kind: Service
metadata:
  name: {{ include "nimbuscore.api.fullname" . }}
  labels: {{ include "nimbuscore.api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "nimbuscore.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
