apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nimbuscore
  namespace: argocd
spec:
  description: NimbusCore platform
  sourceRepos:
    - "https://github.com/nimbuscore/nimbuscore"
  destinations:
    - namespace: "nimbuscore-*"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
